In [1]:
## Part 0: Importing libraries

In [2]:
#Importing Librarys

# Import NumPy for numerical computing
import numpy as np

# Import Pandas for DataFrames
import pandas as pd

# Import Matplotlib for visulization
from matplotlib import pyplot as plt

# Import Seaborn for easier visulization
import seaborn as sns

In [3]:
##Part 1: Data

In [4]:
#You can find my data source here https://www.kaggle.com/datasets/thedevastator/uncover-the-mystery-behind-got-characters-screen on kaggle

In [5]:
##Part 2: Importing

In [6]:
# Import the data from csv file saved locally that I will be using.
GOT = pd.read_csv('screentime.csv')

In [7]:
## Part 3: Preparation

In [8]:
# Display the top of the data frame to see what we are working with.
GOT.head()

,index,name,imdbUrl,screentime,episodes,portrayedBy
0,0,Tyrion Lannister,http://www.imdb.com/character/ch0146096/,293.30,54,"{'name': 'Peter Dinklage', 'imdbUrl': 'http://..."
1,1,Jon Snow,http://www.imdb.com/character/ch0155777/,268.15,49,"{'name': 'Kit Harington', 'imdbUrl': 'http://w..."
2,2,Daenerys Targaryen,http://www.imdb.com/character/ch0158597/,221.30,49,"{'name': 'Emilia Clarke', 'imdbUrl': 'http://w..."
3,3,Cersei Lannister,http://www.imdb.com/character/ch0159526/,201.45,52,"{'name': 'Lena Headey', 'imdbUrl': 'http://www..."
4,4,Sansa Stark,http://www.imdb.com/character/ch0158137/,199.30,47,"{'name': 'Sophie Turner', 'imdbUrl': 'http://w..."

In [9]:
#Sorting, indexing, grouping, Drop duplicates, replace missing values and removing not required columns

In [10]:
# Remove 'imdbUrl' and 'portrayedBy' columns from the DataFrame as they are unneeded.
GOT = GOT.drop(['imdbUrl', 'portrayedBy'], axis=1)

In [11]:
# Sorting the DataFrame by 'screentime' column in descending order
GOT = GOT.sort_values(by='screentime', ascending=False)
# Display the modified DataFrame
GOT.head(10)

   index                name  screentime episodes
0      0    Tyrion Lannister      293.30       54
1      1            Jon Snow      268.15       49
2      2  Daenerys Targaryen      221.30       49
3      3    Cersei Lannister      201.45       52
4      4         Sansa Stark      199.30       47
5      5          Arya Stark      189.15       47
6      6     Jaime Lannister      162.30       43
7      7       Theon Greyjoy      123.30       39
8      8       Samwell Tarly      121.45       37
9      9       Jorah Mormont      117.30       42

In [12]:
# Indexing the DataFrame by the 'index' column
GOT = GOT.set_index('index')
# Display the modified DataFrame from the bottom - take not off Lollys stokworth index 186 as this will need to be replaced later
GOT.tail()

                    name  screentime     episodes
index
186    Lollys Stokeworth        1.45  unspecified
187              Mhaegen        1.15            2
188                Biter        1.15            5
189                Lhara        1.15            3
190           Tobho Mott        1.15            2

In [13]:
# Replace missing values named 'unspecified' in the 'episodes' column with 1
GOT['episodes'] = GOT['episodes'].replace('unspecified', 1)

# Display the modified DataFrame - note: Lollys stokworth index 186 has changed to 1 from unspecified
GOT.tail()

                    name  screentime episodes
index
186    Lollys Stokeworth        1.45        1
187              Mhaegen        1.15        2
188                Biter        1.15        5
189                Lhara        1.15        3
190           Tobho Mott        1.15        2

In [14]:
# Dropping duplicates based on the 'screentime' column.
GOT = GOT.drop_duplicates(subset='screentime')

# Display the DataFrame and show how many rows left after preparing the data for analysis
print(GOT)

                     name  screentime episodes
index
0        Tyrion Lannister      293.30       54
1                Jon Snow      268.15       49
2      Daenerys Targaryen      221.30       49
3        Cersei Lannister      201.45       52
4             Sansa Stark      199.30       47
...                   ...         ...      ...
177                 Daisy        2.30        3
179            Ilyn Payne        2.15        4
181        Ternesio Terys        2.00        2
182               Quaithe        1.45        2
187               Mhaegen        1.15        2

[111 rows x 3 columns]

In [15]:
## Part 4: Analysis

In [16]:
#Creating a panda data frame as part of the milestone as an example of creating pandas data frame

# Create a DataFrame from a dictionary
Example = {'index': [0, 1, 3],   
       'rating': [5, 6, 9]}
eg = pd.DataFrame(Example)

# Display the DataFrame
eg.head()

   index  rating
0      0       5
1      1       6
2      3       9

In [17]:
# Merge the 'eg' DataFrame with the 'GOT' DataFrame based on the 'index' column as part of the milestones as an example of merging
GOTeg1 = pd.merge(eg, GOT, on='index', how='left')

# Display the merged DataFrame
GOTeg1.head()

   index  rating              name  screentime episodes
0      0       5  Tyrion Lannister      293.30       54
1      1       6          Jon Snow      268.15       49
2      3       9  Cersei Lannister      201.45       52

In [18]:
# Group the 'GOT' DataFrame by the 'episodes' column and calculate the sum of 'screentime' for each episode count as part of the milestones as an example of grouping
grouped_GOT = GOT.groupby('episodes').sum()

# Display the grouped data
grouped_GOT.head(10)

          screentime
episodes
10             62.15
11             37.60
12            106.20
13             44.60
14             70.20
15             14.15
16            167.05
17             91.75
18             42.30
19             56.15